name: ci

on: 
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"

    - name: Tests
      run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"

    - name: Check PWD
      run: pwd

    - name: Check formatting
      run: |
        UNFORMATTED=$(go fmt ./...)
        if [ ! -z "$UNFORMATTED" ]; then
          echo "The following files need formatting:"
          echo "$UNFORMATTED"
          echo "Please run 'go fmt ./...' locally"
          # Optional: Remove the line below if you don't want the pipeline to fail
          exit 1
        else
          echo "✅ Code formatting is correct"
        fi