name: evets

run-name: Inputs | DEBUG - ${{ inputs.debug }}

on: 
  push:
  pull_request:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:

  
  echo-data:
    runs-on: ubuntu-latest
    steps:

      - name: Echo event name
        run: |
          echo "Event name is ${{ github.event_name }}"
          echo "Ref is ${{ github.ref }}"
          echo "Repository is ${{ github.repository }}"
          echo "Actor is ${{ github.actor }}"
          echo "Workflow is ${{ github.workflow }}"
          echo "Event action is ${{ github.event.action || 'N/A' }}"
          echo "Run Id is ${{ github.run_id }}"
          echo "Run number is ${{ github.run_number }}"
          echo "SHA is ${{ github.sha }}"


      - name: Retrieve Variables
        run: |
          echo "Variable value: ${{ vars.TEST_VAR }}"
