name: Inputs
run-name: Inputs | DEBUG - ${{ inputs.debug }} | run number - ${{ github.run_number }} 

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false
        

jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.enet_name }}"
          echo "Branch:       ${{ github.ref }}"
          echo "Commit SHA:   ${{ github.sha }}"
          echo "Runners OS:   ${{ runner.os }}"
          echo "Repository:   ${{ github.repository }}"
          echo "Actor:        ${{ github.actor }}"
          echo "Event Action: ${{ github.event.action || 'N/A' }}"
          echo "Event Name:   ${{ github.event_name }}"
          echo "Run ID:       ${{ github.run_id }}"
          echo "Run Number:   ${{ github.run_number }}"
